
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Install yum packages
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python-pip
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - amazon-linux-extras
    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Container with Jenkins
      shell: docker run -p 8080:8080 -p 50000:50000 jenkins:2.60.3
